### ISSUE TITLE
Please update Cypress Programmer -> ModusToolbox Programming Tools

### ISSUE THREAD

**Issue by mykz-cy** [avnet-iotconnect/avnet-iotc-mtb-xensiv-example#2]
Hey Avnet Team!
Congrats with releasing the solution for IOT. Just few days ago we have release ModusToolbox Programming Tools package which includes the mtb-programmer UI and replaces the Cypress Programmer. You might want to update your Guide to include the reference to that and to download ModusToolbox Programming Tools instead of Cypress Programmer: https://www.infineon.com/cms/en/design-support/tools/programming-testing/psoc-programming-solutions/

Thanks!
   Mykhailo

**Comment by shu-liu1314** [comment]
Mykhailo,

We did update the guide to use ModusToolbox Programming Tools. Thanks for letting us know.
